### ISSUE TITLE
discussion aftrer enable_logger was implemented

### ISSUE THREAD

**Issue by atus42** [TheStaticTurtle/esphome_syslog#2]
Hello!

I probably confused by all the github windows in my browser, and wrote in the wrong window.
Because I don't need all my logger messages to forward to syslog, it was easier to me to delete that part of your code in my implementation, than make a pull request and make it configurable.

I need the syslog forwarding in a lambda function, therefore the example.
On the other hand, I don't know how to use your code in yaml coding. Well.. rereading your description answered that question.
I must have been very tired not to notice that.

Best regards,
Atus

**Comment by atus42** [comment]
I just looked the yaml syntax again, and noticed that probably it is not capable of templating. 
By templating I mean something like this:

```
sensor:
  - platform: wifi_signal
    name: "WiFi (${my_name})"
    id: sensor_wifi_signal_${my_name}
    update_interval: 30s
    on_raw_value:
      then:
        logger.log:
          format: "sensor sensor_wifi_signal_${my_name} got value %.1f"
          args: [ 'id(sensor_wifi_signal_${my_name}).state']
          level: INFO
```
Can the `payload` contain variables? I usually use variables in my logger mesages like the above.

**Comment by TheStaticTurtle** [comment]
No, args in this format are not supported, I might try to support it in the future but right now it isn't a priority. Using a lambda function might be easier can you post an example I've never worked with them before

**Comment by atus42** [comment]
I used your code from lambda like this:
```
      then:
        - lambda: !lambda |-
            char sprintf_buff[50];
            ESP_LOGD("new_epoch", "\t epoch_time (old) (%s)", set_or_get_time( id(epoch_time).timestamp_now(), 0 ).c_str() );
            ESP_LOGD("new_epoch", "\t epoch_time (new) (%s)", set_or_get_time( epoch, 1 ).c_str() );
            sprintf(sprintf_buff, "epoch_time (old) (%s)", set_or_get_time( id(epoch_time).timestamp_now(), 0 ).c_str() );
            my_syslog->log(LOG_INFO, "${my_name}", sprintf_buff );
            sprintf(sprintf_buff, "epoch_time (new) (%s)", set_or_get_time( epoch, 1 ).c_str() );
            my_syslog->log(LOG_INFO, "${my_name}", sprintf_buff );
```
`set_or_get_time` is a function of mine which converts epoch time to humanly readable string.
I hope this helps.

**Comment by TheStaticTurtle** [comment]
Ok thanks

**Comment by atus42** [comment]
I tried to use the yaml version:

```
           - syslog.log:
               level: 6
               tag: ${my_name}
               payload: "on_loop turned OFF heating"
```
but got compilation error:
```
src/main.cpp:1157:29: error: 'class esphome::syslog::SyslogLogAction<bool>' has no member named 'set_topic'
   syslog_sysloglogaction_5->set_topic(6);
                             ^
src/main.cpp:1160:29: error: 'class esphome::syslog::SyslogLogAction<bool>' has no member named 'set_topic'
   syslog_sysloglogaction_5->set_topic("esp_futes");
                             ^
```
unfortunately I was unable to figure out how to correct the error.
I see, that you define the set_topic action two times:
```
    template_ = yield cg.templatable(config[CONF_LEVEL], args, cg.uint8)
    cg.add(var.set_topic(template_))
    template_ = yield cg.templatable(config[CONF_TAG], args, cg.std_string)
    cg.add(var.set_topic(template_))
```
