### ISSUE TITLE
Setup failed for syslog: No setup or config entry setup function defined.  Error setup.py

### ISSUE THREAD

**Issue by candeo911** [TheStaticTurtle/esphome_syslog#8]
Fails right out the gate.  Not sure what's wrong here.

[esp syslog issues.txt](https://github.com/TheStaticTurtle/esphome_syslog/files/9480450/esp.syslog.issues.txt)

**Comment by TheStaticTurtle** [comment]
I was a bit confused by your issue at first 😅 but here is the issue:
This is a custom component for **esphome** to forward esphome node logs to a syslog server, **not** for HomeAssistant itself.
Here I see that you added a `syslog:` section to your HomeAssistant config for which HA doesn't know what to do, hence the error.

Here is a part of the config of one of my esphome node:
```
esphome:
  name: esp_sonette
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

syslog:
  ip_address: "192.168.1.53"
  min_level: DEBUG
```

Here `192.168.1.53` is not HomeAssistant ip, it's the address of the syslog server that's ingesting the logs from every node

As for my HomeAssistant config, it needs no changes as this component does not interact with it
