### ISSUE TITLE
Looking for better code examples in the documentation for setting up syslog.log using deep verbose mode.

### ISSUE THREAD

**Issue by candeo911** [TheStaticTurtle/esphome_syslog#9]
my current snip of yaml thats works just fine using your code:

```yaml
esp8266:
  board: nodemcuv2

# Enable logging
logger:

syslog:
  ip_address: "192.168.10.101"
  port: 1518
  min_level: DEBUG

# Enable Home Assistant API
api:
```

I would like it so that I do not get the "basic" operations logged to my graylog server but the deeper level debug information such as when the unit gets updated, update failures, reboots, any kind of low level errors, etc.  So I attempted the below but based on the examples in the documentation, they just don't make sense and the YAML will not compile.  Can you please provide a clear code example of how this is accomplished to obtain `ESPHOME_LOG_LEVEL_VERY_VERBOSE` / `LOG_DEBUG` level capture to graylog?  Interestingly Logspout can send data to Graylog using GELF if at all possible to capture more information and a greater calirty as well instead of using syslog.

```yaml
syslog:
  ip_address: "192.168.10.101"
  port: 1518
  min_level: DEBUG
  then:
    - syslog.log:
        level: 7
        tag: "custom_action"
        payload: "My log message"
```

I also tried the below:

```yaml
syslog.log:
  ip_address: "192.168.10.101"
  port: 1518
  level: 7
  tag: "custom_action"
  payload: "My log message"
```

**Comment by TheStaticTurtle** [comment]
Hello,
First, I took the liberty to properly format your issue with code blocks (\`\`\`).

By default, the syslog component will use the level `DEBUG` as minimum, and you will see these messages as DEBUG in your syslog server.
If you want to enable the `VERY_VERBOSE` level, you can do so like this:
```yaml
logger:
  level: VERY_VERBOSE

syslog:
  ip_address: "192.168.10.101"
  port: 1518
  min_level: VERY_VERBOSE
```

Unfortunately, syslog does not support the `VERY_VERBOSE` level, it is an ESPHome only setting. This is why there is a translation table in the README. The ESPHome levels named `DEBUG` `VERBOSE` and `VERY_VERBOSE` will be sent as `DEBUG` to the syslog server

I'm not familiar with Graylog, nor am I with Logspout, so I can't really help you there.

On another note, `syslog.log` is an action, not the configuration for the component. You can use it like this, for example: 
```yaml
binary_sensor:
  - platform: esp32_touch
    internal: true
    name: "Button"
    pin: GPIO27
    threshold: 1000
    on_press:
      - syslog.log:
          level: 7
          tag: "custom_action"
          payload: "My log message"
```
